# Copyright (c) 2018-2022 Margarita Colberg
# SPDX-License-Identifier: BSD-3-Clause

name: format C++ code

on:
  push:
    paths:
      - .github/workflows/format.yml
      - src/**.cc
      - src/**.h
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: sudo apt-get -y -qq update

      - run: sudo apt-get -y -qq install clang-format

      # https://clang.llvm.org/docs/ClangFormat.html
      - run: find src/ \( -name '*.cc' -or -name '*.h' \) -exec clang-format -i --style=LLVM {} +
      - run: git diff --exit-code > clang-format.diff

      - if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          # apply to local repository with:
          # patch -p1 < clang-format.diff
          name: hybridmc_clang_format
          path: clang-format.diff
